// Code generated by "stringer -trimprefix pageType -type pageType"; DO NOT EDIT.

package bdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[pageTypeInvalid-0]
	_ = x[pageTypeDuplicate-1]
	_ = x[pageTypeHashUnsorted-2]
	_ = x[pageTypeIBTree-3]
	_ = x[pageTypeIRecNo-4]
	_ = x[pageTypeLBTree-5]
	_ = x[pageTypeLRecNo-6]
	_ = x[pageTypeOverflow-7]
	_ = x[pageTypeHashMeta-8]
	_ = x[pageTypeBTreeMeta-9]
	_ = x[pageTypeQAMMeta-10]
	_ = x[pageTypeQAMData-11]
	_ = x[pageTypeLDup-12]
	_ = x[pageTypeHash-13]
	_ = x[pageTypeHeapMeta-14]
	_ = x[pageTypeHeap-15]
	_ = x[pageTypeIHeap-16]
	_ = x[pageTypeMax-17]
}

const _pageType_name = "InvalidDuplicateHashUnsortedIBTreeIRecNoLBTreeLRecNoOverflowHashMetaBTreeMetaQAMMetaQAMDataLDupHashHeapMetaHeapIHeapMax"

var _pageType_index = [...]uint8{0, 7, 16, 28, 34, 40, 46, 52, 60, 68, 77, 84, 91, 95, 99, 107, 111, 116, 119}

func (i pageType) String() string {
	if i >= pageType(len(_pageType_index)-1) {
		return "pageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pageType_name[_pageType_index[i]:_pageType_index[i+1]]
}
